/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "gold": "#cba258",
        "secondary-container": "#97f6c0",
        "surface-variant": "#e0e3de",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e0e3de",
        "canvas-warm": "#f2f0eb",
        "surface-container-high": "#e6e9e4",
        "secondary": "#006c44",
        "surface": "#f7faf5",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eef2ec",
        "on-primary-container": "#8bdbb1",
        "primary": "#00482f",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "outline-variant": "#bec9c0",
        "on-secondary-container": "#007349",
        "outline": "#6f7a72",
        "green-light": "#d4e9e2",
        "on-surface": "#181d1a",
        "on-tertiary-container": "#b3d1c7",
        "on-secondary-fixed": "#002112",
        "gold-light": "#dfc49d",
        "neutral-cool": "#f9f9f9",
        "ceramic": "#edebe9",
        "gold-lightest": "#faf6ee",
        "surface-tint": "#146b4a",
        "on-background": "#181d1a",
        "on-primary-fixed": "#002113",
        "on-tertiary-fixed": "#04201a",
        "surface-bright": "#f7faf5",
        "tertiary-fixed-dim": "#afcdc3",
        "secondary-fixed": "#97f6c0",
        "primary-container": "#006241",
        "surface-container-low": "#f1f5ef",
        "on-secondary-fixed-variant": "#005232",
        "primary-fixed-dim": "#87d7ad",
        "inverse-primary": "#87d7ad",
        "green-uplift": "#2b5148",
        "surface-container": "#ebefea",
        "primary-fixed": "#a2f3c8",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#405b53",
        "secondary-fixed-dim": "#7cd9a5",
        "inverse-surface": "#2d312e",
        "background": "#f7faf5",
        "surface-dim": "#d7dbd6",
        "on-tertiary-fixed-variant": "#314c44",
        "error-container": "#ffdad6",
        "rewards-slate": "#33433d",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#005235",
        "tertiary": "#28433c",
        "tertiary-fixed": "#cbe9df",
        "on-surface-variant": "#3f4943"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-3": "1.6rem",
        "space-7": "6.4rem",
        "base": "1.6rem",
        "space-5": "3.2rem",
        "space-1": "0.4rem",
        "space-6": "4.8rem",
        "space-2": "0.8rem",
        "space-4": "2.4rem"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-serif": ["Literata", "serif"],
        "script-touch": ["Karla", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.16px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "-0.16px", fontWeight: "400" }],
        "body-lg": ["19px", { lineHeight: "1.5", letterSpacing: "-0.16px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.16px", fontWeight: "700" }],
        "headline-serif": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "script-touch": ["18px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.16px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
};
